import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#FFFDF0" },
  scrollContainer: { paddingBottom: 60 },
  blob: {
    position: "absolute",
    backgroundColor: "#FFE8A3",
    opacity: 0.2,
    borderRadius: 1000,
  },
  blobTop: { width: 600, height: 600, top: -200 },
  blobBottom: { width: 500, height: 500, bottom: 50 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 30,
    marginBottom: 20,
  },
  backBtn: {
    width: 48,
    height: 48,
    backgroundColor: "white",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E5E0D5",
    elevation: 2,
  },
  headerTitleContainer: { alignItems: "center" },
  storefrontLabel: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  labelIndicator: {
    width: 4,
    height: 12,
    backgroundColor: "#FBBF24",
    borderRadius: 2,
    marginRight: 6,
  },
  storefrontText: {
    fontSize: 10,
    fontWeight: "900",
    color: "#A5A58D",
    letterSpacing: 2,
  },
  mainTitle: { fontSize: 24, fontWeight: "900", color: "#1A1A1A" },
  sparkleContainer: {
    width: 48,
    height: 48,
    backgroundColor: "white",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#F3EEE0",
  },
  photoContainer: { width: "100%", marginVertical: 24 },
  imagePicker: {
    width: "100%",
    aspectRatio: 4 / 3,
    backgroundColor: "white",
    borderRadius: 40,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: "#E5E0D5",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  imagePickerActive: { borderStyle: "solid", borderColor: "#FBBF24" },
  previewImage: { width: "100%", height: "100%", resizeMode: "cover" },
  removePhotoBtn: {
    position: "absolute",
    top: 15,
    right: 15,
    backgroundColor: "rgba(92, 22, 22, 0.8)",
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
  },
  imagePickerContent: { alignItems: "center", justifyContent: "center" },
  cameraIconBg: {
    width: 64,
    height: 64,
    backgroundColor: "#FFFDF0",
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#F3EEE0",
  },
  imagePickerTitle: { fontSize: 14, fontWeight: "900", color: "#1A1A1A" },
  imagePickerSub: {
    fontSize: 9,
    fontWeight: "700",
    color: "#A5A58D",
    letterSpacing: 1,
    marginTop: 4,
  },
  form: { gap: 20 },
  field: { gap: 8 },
  label: {
    fontSize: 11,
    fontWeight: "900",
    color: "#6B705C",
    letterSpacing: 1.5,
    marginLeft: 4,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#E5E0D5",
    height: 58,
    paddingHorizontal: 16,
  },
  icon: { marginRight: 12 },
  input: { flex: 1, fontSize: 15, fontWeight: "700", color: "#1A1A1A" },
  currencySymbol: {
    fontSize: 16,
    fontWeight: "900",
    color: "#5c1616",
    marginRight: 4,
  },
  row: { flexDirection: "row" },
  dropdownTrigger: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "white",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#E5E0D5",
    height: 58,
    paddingHorizontal: 20,
  },
  dropdownText: { fontSize: 14, fontWeight: "700", color: "#1A1A1A" },
  dropdownList: {
    backgroundColor: "white",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#E5E0D5",
    padding: 8,
    marginTop: 4,
    elevation: 4,
  },
  dropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 14,
    borderRadius: 12,
  },
  itemText: { fontSize: 14, fontWeight: "700", color: "#1A1A1A" },
  tips: {
    flexDirection: "row",
    backgroundColor: "rgba(92, 22, 22, 0.05)",
    borderRadius: 32,
    padding: 10,
    alignItems: "center",
    gap: 16,
    marginTop: 20,
  },
  infoIcon: {
    width: 22,
    height: 22,
    backgroundColor: "#5c1616",
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  tipsText: {
    flex: 1,
    fontSize: 10,
    fontWeight: "900",
    color: "#5c1616",
    letterSpacing: 0.5,
    lineHeight: 14,
  },
  publishBtn: {
    backgroundColor: "#1A1A1A",
    height: 72,
    borderRadius: 28,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 30,
    gap: 20,
    elevation: 8,
  },
  publishText: {
    color: "white",
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: 4,
  },
  checkIcon: {
    width: 40,
    height: 40,
    backgroundColor: "#FBBF24",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  footer: { marginTop: 60, alignItems: "center", opacity: 0.4 },
  footerLine: {
    width: 60,
    height: 2,
    backgroundColor: "#FBBF24",
    marginBottom: 20,
  },
  brand: {
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 8,
    color: "#7A6B44",
  },
  tagline: {
    fontSize: 9,
    fontWeight: "900",
    color: "#A5A58D",
    letterSpacing: 3,
    marginTop: 8,
  },
});