import { Dimensions, Platform, StyleSheet } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FFFDF0" },
  scrollContainer: { paddingBottom: 60 },
  blob: {
    position: "absolute",
    backgroundColor: "#FFE8A3",
    opacity: 0.2,
    borderRadius: 1000,
  },
  blobTop: { width: 600, height: 600, top: -200 },
  blobBottom: { width: 500, height: 500, bottom: 50 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 15,
  },
  iconBtn: {
    width: 45,
    height: 45,
    backgroundColor: "white",
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E5E0D5",
  },
  iconBtnEmpty: {
    width: 45,
    height: 45,
    backgroundColor: "rgba(255,255,255,0.5)",
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#F3EEE0",
  },
  headerTitleArea: { alignItems: "center" },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 4,
  },
  badgeText: {
    fontSize: 10,
    fontWeight: "900",
    color: "#A5A58D",
    letterSpacing: 2,
  },
  title: { fontSize: 24, fontWeight: "900", color: "#1A1A1A" },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 20,
    marginVertical: 20,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: "900",
    color: "#5c1616",
    letterSpacing: 1.5,
  },
  imageCard: {
    marginHorizontal: 20,
    aspectRatio: 4 / 3,
    backgroundColor: "white",
    borderRadius: 35,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: "#E5E0D5",
    overflow: "hidden",
  },
  imageWrapper: { width: "100%", height: "100%" },
  fullImage: { width: "100%", height: "100%", resizeMode: "cover" },
  closeBtn: {
    position: "absolute",
    top: 15,
    right: 15,
    backgroundColor: "rgba(0,0,0,0.6)",
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  imagePlaceholder: { flex: 1, justifyContent: "center", alignItems: "center" },
  cameraCircle: {
    width: 60,
    height: 60,
    backgroundColor: "#FFFDF0",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#F3EEE0",
  },
  uploadMainText: { fontSize: 14, fontWeight: "900", color: "#1A1A1A" },
  uploadSubText: {
    fontSize: 9,
    fontWeight: "800",
    color: "#A5A58D",
    marginTop: 4,
    letterSpacing: 1,
  },
  formSection: { paddingHorizontal: 20, marginTop: 25 },
  inputGroup: { marginBottom: 18 },
  label: {
    fontSize: 10,
    fontWeight: "900",
    color: "#6B705C",
    letterSpacing: 1,
    marginBottom: 8,
    marginLeft: 5,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E5E0D5",
    paddingHorizontal: 15,
  },
  inputIcon: { marginRight: 10 },
  input: {
    flex: 1,
    height: 55,
    fontSize: 15,
    fontWeight: "700",
    color: "#1A1A1A",
  },
  row: { flexDirection: "row" },
  dropdown: {
    height: 55,
    backgroundColor: "white",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E5E0D5",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 15,
  },
  dropdownText: { fontSize: 14, fontWeight: "700", color: "#1A1A1A" },
  lockedInput: { backgroundColor: "#F5F5F5", opacity: 0.6 },
  inputSimple: {
    height: 55,
    backgroundColor: "white",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E5E0D5",
    paddingHorizontal: 15,
    fontSize: 14,
    fontWeight: "700",
  },
  textAreaWrapper: {
    flexDirection: "row",
    backgroundColor: "white",
    borderRadius: 25,
    borderWidth: 1,
    borderColor: "#E5E0D5",
    padding: 15,
  },
  textAreaIcon: { marginTop: 5, marginRight: 10 },
  textArea: {
    flex: 1,
    height: 100,
    fontSize: 15,
    fontWeight: "700",
    textAlignVertical: "top",
  },
  infoBox: {
    backgroundColor: "rgba(92, 22, 22, 0.05)",
    borderRadius: 25,
    padding: 15,
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
    gap: 15,
  },
  infoIcon: {
    width: 35,
    height: 35,
    backgroundColor: "#5c1616",
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  infoText: {
    flex: 1,
    fontSize: 10,
    fontWeight: "900",
    color: "#5c1616",
    opacity: 0.8,
    letterSpacing: 0.5,
  },
  primaryBtn: {
    backgroundColor: "#1A1A1A",
    height: 70,
    borderRadius: 25,
    marginTop: 30,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 15,
    elevation: 5,
  },
  primaryBtnText: {
    color: "white",
    fontSize: 14,
    fontWeight: "900",
    letterSpacing: 3,
  },
  primaryBtnIcon: {
    width: 40,
    height: 40,
    backgroundColor: "#FBBF24",
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  footer: { marginTop: 50, alignItems: "center", opacity: 0.3 },
  footerLine: {
    width: 40,
    height: 2,
    backgroundColor: "#FBBF24",
    marginBottom: 15,
  },
  brand: {
    fontSize: 12,
    fontWeight: "900",
    color: "#7A6B44",
    letterSpacing: 10,
  },
  tagline: {
    fontSize: 8,
    fontWeight: "900",
    color: "#A5A58D",
    marginTop: 8,
    letterSpacing: 4,
  },
  modalContent: {
    backgroundColor: "white",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: 20,
    maxHeight: height * 0.7,
  },
  optionItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: "#FDFCF6",
  },
  optionLabel: { fontSize: 16, fontWeight: "700", color: "#1A1A1A" },
  labelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  infoIconBtn: {
    padding: 2,
  },
  disabledLabel: {
    color: "#A5A58D",
  },
  disabledText: {
    color: "#A5A58D",
  },
  animatedIn: { transform: [{ translateY: 0 }] },
  modalHandle: {
    width: 40,
    height: 5,
    backgroundColor: "#E5E0D5",
    borderRadius: 10,
    alignSelf: "center",
    marginBottom: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  titleWrapper: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  headerIconBg: {
    width: 36,
    height: 36,
    backgroundColor: "#5c1616",
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: "#1A1A1A",
  },
  closeCircle: {
    width: 36,
    height: 36,
    backgroundColor: "#F3EEE0",
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
  },
  introText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#6B705C",
    lineHeight: 20,
    marginBottom: 24,
  },
  ruleCard: {
    flexDirection: "row",
    backgroundColor: "white",
    padding: 16,
    borderRadius: 24,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#EFE8DA",
    gap: 16,
  },
  ruleIconBg: {
    width: 32,
    height: 32,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  ruleTextContent: {
    flex: 1,
  },
  ruleTitle: {
    fontSize: 14,
    fontWeight: "900",
    color: "#1A1A1A",
    marginBottom: 4,
  },
  ruleDescription: {
    fontSize: 12,
    fontWeight: "600",
    color: "#A5A58D",
    lineHeight: 18,
  },
  modalFooter: {
    marginTop: 20,
    marginBottom: 10,
  },
  understandBtn: {
    backgroundColor: "#1A1A1A",
    paddingVertical: 18,
    borderRadius: 20,
    alignItems: "center",
    shadowColor: "#1A1A1A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  understandBtnText: {
    color: "white",
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 2,
  },
  rulesContent: {
    flex: 1,
    marginTop: 5,
    marginBottom: 10,
  },
  rulesModal: {
    backgroundColor: "#FFFDF0",
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    paddingTop: 12,
    paddingHorizontal: 24,
    minHeight: 400,
    width: "100%",
    zIndex: 1000,
    elevation: 5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  navigationWrapper: {
    width: "100%",
    alignItems: "center",
    marginTop: 27,
  },
  navigationContainer: {
    width: "87%",
    flexDirection: "row",
    justifyContent: "center",
    backgroundColor: "white",
    borderRadius: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E0D5",
    paddingHorizontal: 10,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
      },
      android: {
        elevation: 3,
      },
    }),
  },

  navigationTab: {
    flex: 1,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    borderBottomWidth: 3,
    borderBottomColor: "transparent",
  },
  navigationTabActive: {
    borderBottomColor: "#5c1616",
  },
  navigationTabText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#A5A58D",
    letterSpacing: 0.5,
  },
  navigationTabTextActive: {
    color: "#5c1616",
    fontWeight: "900",
  },
});
