import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#FFFDF0",
  },
  blobContainer: {
    ...StyleSheet.absoluteFillObject,
    overflow: "hidden",
  },
  blob1: {
    position: "absolute",
    width: 600,
    height: 600,
    borderRadius: 300,
    backgroundColor: "#FFE8A3",
    top: -200,
    right: -150,
    opacity: 0.3,
  },
  blob2: {
    position: "absolute",
    width: 500,
    height: 500,
    borderRadius: 250,
    backgroundColor: "#FFF1C1",
    bottom: "10%",
    left: -150,
    opacity: 0.2,
  },
  scrollContainer: {
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 20,
    paddingBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: "#F3EEE0",
  },
  iconButton: {
    width: 48,
    height: 48,
    backgroundColor: "white",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#E5E0D5",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
      },
      android: { elevation: 2 },
    }),
  },
  headerTitleGroup: {
    alignItems: "center",
  },
  headerBadge: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  badgeLine: {
    width: 4,
    height: 12,
    backgroundColor: "#FBBF24",
    borderRadius: 2,
    marginRight: 8,
  },
  headerBadgeText: {
    fontSize: 10,
    fontWeight: "900",
    color: "#A5A58D",
    letterSpacing: 2.5,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: "#1A1A1A",
    letterSpacing: -0.5,
  },
  section: {
    marginTop: 32,
  },
  label: {
    fontSize: 11,
    fontWeight: "900",
    color: "#6B705C",
    letterSpacing: 1.5,
    marginBottom: 12,
    marginLeft: 4,
  },
  uploadZone: {
    width: "100%",
    height: 180,
    backgroundColor: "white",
    borderRadius: 40,
    borderWidth: 2,
    borderColor: "#E5E0D5",
    borderStyle: "dashed",
    alignItems: "center",
    justifyContent: "center",
  },
  uploadIconContainer: {
    width: 64,
    height: 64,
    backgroundColor: "#FFFDF0",
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#F3EEE0",
  },
  uploadMainText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#1A1A1A",
  },
  uploadSubText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#A5A58D",
    marginTop: 4,
    letterSpacing: 1,
  },
  fileCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 32,
    padding: 20,
    borderWidth: 1,
    borderColor: "#5c1616",
  },
  fileIconContainer: {
    width: 48,
    height: 48,
    backgroundColor: "#5c16160D",
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  fileName: {
    fontSize: 14,
    fontWeight: "900",
    color: "#1A1A1A",
  },
  fileSize: {
    fontSize: 10,
    fontWeight: "800",
    color: "#A5A58D",
    letterSpacing: 1,
    marginTop: 2,
  },
  trashBtn: {
    padding: 8,
  },
  formContainer: {
    marginTop: 32,
    gap: 24,
  },
  inputGroup: {
    gap: 8,
  },
  labelRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingRight: 4,
    marginBottom: 8,
  },
  optionalText: {
    fontSize: 9,
    fontWeight: "900",
    color: "#A5A58D",
    letterSpacing: 1,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#E5E0D5",
    paddingHorizontal: 20,
    height: 58,
  },
  leftIcon: {
    marginRight: 12,
  },
  textInput: {
    flex: 1,
    fontSize: 15,
    fontWeight: "700",
    color: "#1A1A1A",
  },
  dropdownTrigger: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "white",
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#E5E0D5",
    paddingHorizontal: 24,
    height: 58,
  },
  dropdownValue: {
    fontSize: 14,
    fontWeight: "700",
  },
  dropdownMenu: {
    backgroundColor: "white",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#E5E0D5",
    padding: 8,
    marginTop: 4,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
      },
      android: { elevation: 10 },
    }),
  },
  dropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 16,
  },
  itemText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1A1A1A",
  },
  infoBox: {
    marginTop: 32,
    flexDirection: "row",
    backgroundColor: "#5c16160D",
    borderRadius: 32,
    padding: 24,
    borderWidth: 1,
    borderColor: "#5c16161A",
    gap: 16,
  },
  infoIconCircle: {
    width: 44,
    height: 44,
    backgroundColor: "#5c1616",
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  infoText: {
    flex: 1,
    fontSize: 10,
    fontWeight: "900",
    color: "#5c1616CC",
    lineHeight: 16,
    letterSpacing: 0.5,
  },
  publishBtn: {
    marginTop: 32,
    width: "100%",
    height: 72,
    backgroundColor: "#1A1A1A",
    borderRadius: 28,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 20,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.3,
        shadowRadius: 16,
      },
      android: { elevation: 8 },
    }),
  },
  publishBtnText: {
    color: "white",
    fontSize: 15,
    fontWeight: "900",
    letterSpacing: 3,
    textTransform: "uppercase",
  },
  checkIconBox: {
    width: 40,
    height: 40,
    backgroundColor: "#FBBF24",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  footer: {
    marginTop: 64,
    alignItems: "center",
    opacity: 0.4,
  },
  footerLine: {
    width: 60,
    height: 2,
    backgroundColor: "#FBBF24",
    borderRadius: 2,
    marginBottom: 24,
  },
  footerBrand: {
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 8,
    color: "#7A6B44",
  },
  footerTag: {
    fontSize: 9,
    fontWeight: "800",
    color: "#A5A58D",
    letterSpacing: 2,
    marginTop: 12,
  },
});