import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#FFFDF0" },
  header: {
    padding: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  title: { fontSize: 22, fontWeight: "900" },
  badgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 4,
  },
  badgeText: {
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 2,
    color: "#B07D05",
  },
  postBtn: {
    flexDirection: "row",
    gap: 6,
    backgroundColor: "#1A1A1A",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 18,
  },
  postText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "900",
    letterSpacing: 1,
  },
  searchBox: {
    marginHorizontal: 20,
    marginBottom: 20,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  searchInput: { flex: 1, marginLeft: 10 },
  infoBanner: {
    marginHorizontal: 20,
    backgroundColor: "#5c1616",
    borderRadius: 24,
    padding: 16,
    flexDirection: "row",
    gap: 12,
    marginBottom: 20,
  },
  infoIcon: {
    backgroundColor: "rgba(255,255,255,0.1)",
    padding: 8,
    borderRadius: 12,
  },
  infoTitle: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 2,
  },
  infoText: {
    color: "rgba(255,255,255,0.7)",
    fontSize: 10,
    marginTop: 4,
  },
  count: {
    marginHorizontal: 20,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 2,
    color: "#6B705C",
    marginBottom: 10,
  },
  list: { paddingHorizontal: 20 },
  card: {
    backgroundColor: "#fff",
    borderRadius: 30,
    padding: 16,
    marginBottom: 14,
    flexDirection: "row",
    gap: 14,
  },
  cover: {
    width: 80,
    height: 112,
    backgroundColor: "#FDFDFB",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  pdfBadge: {
    position: "absolute",
    bottom: 8,
    backgroundColor: "#1A1A1A",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  pdfText: { color: "#fff", fontSize: 8, fontWeight: "900" },
  content: { flex: 1 },
  cardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  genre: {
    fontSize: 8,
    fontWeight: "900",
    backgroundColor: "#F4F1EA",
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    color: "#6B705C",
  },
  bookTitle: { fontSize: 16, fontWeight: "900", marginTop: 4 },
  author: { fontSize: 11, color: "#A5A58D", marginTop: 2 },
  description: {
    fontSize: 10,
    color: "#6B705C",
    fontStyle: "italic",
    marginTop: 8,
  },
  cardBottom: {
    marginTop: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  metaRow: { flexDirection: "row", gap: 12 },
  meta: { flexDirection: "row", alignItems: "center", gap: 4 },
  metaText: { fontSize: 10, fontWeight: "900" },
  metaMuted: { fontSize: 10, color: "#A5A58D" },
  openBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#FBBF24",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  openText: { fontSize: 9, fontWeight: "900" },
  empty: {
    marginTop: 40,
    alignItems: "center",
    padding: 40,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: "#E5E0D5",
    borderRadius: 32,
  },
  emptyTitle: { marginTop: 10, fontWeight: "900" },
  emptyText: { fontSize: 11, color: "#6B705C", marginTop: 4 },
  footer: {
    alignItems: "center",
    marginVertical: 30,
    opacity: 0.3,
  },
  footerLine: {
    width: 32,
    height: 1,
    backgroundColor: "#6B705C",
    marginBottom: 6,
  },
  footerText: {
    fontSize: 9,
    fontWeight: "900",
    letterSpacing: 4,
    color: "#6B705C",
  },
});
