import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");
const CARD_WIDTH = (width - 48 - 16) / 2;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FCF9F1" },
  bgCircle1: {
    position: "absolute",
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: "#F5E6CC",
    top: -100,
    right: -50,
    opacity: 0.4,
  },
  bgCircle2: {
    position: "absolute",
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: "#E8D8C3",
    top: 300,
    left: -50,
    opacity: 0.3,
  },
  scrollContent: { paddingBottom: 40 },
  header: { padding: 24, paddingBottom: 10 },
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  subHeader: {
    fontSize: 10,
    fontWeight: "900",
    color: "#D4AF37",
    letterSpacing: 4,
  },
  mainTitle: {
    fontSize: 32,
    fontWeight: "900",
    color: "#1A1A1A",
    letterSpacing: -1,
  },
  filterIcon: {
    width: 48,
    height: 48,
    backgroundColor: "#FFF",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
  },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF",
    borderRadius: 20,
    paddingHorizontal: 16,
    height: 56,
    elevation: 3,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
  },
  input: {
    flex: 1,
    marginLeft: 10,
    fontSize: 15,
    fontWeight: "600",
    color: "#1A1A1A",
  },
  catWrapper: { marginTop: 20, flexDirection: "row" },
  catBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 14,
    marginRight: 10,
    borderWidth: 1,
    borderColor: "#E5E0D5",
  },
  catBtnActive: { backgroundColor: "#1A1A1A", borderColor: "#1A1A1A" },
  catText: { marginLeft: 8, fontSize: 11, fontWeight: "900", color: "#6B705C" },
  catTextActive: { color: "#FFF" },
  resultsHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 24,
    marginTop: 20,
    marginBottom: 16,
  },
  accentBar: {
    width: 4,
    height: 16,
    backgroundColor: "#721C24",
    borderRadius: 2,
    marginRight: 8,
  },
  resultsText: {
    fontSize: 11,
    fontWeight: "900",
    color: "#6B705C",
    letterSpacing: 1,
  },
  bookGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 24,
    justifyContent: "space-between",
  },
  bookCard: { width: CARD_WIDTH, marginBottom: 30 },
  imagePlaceholder: {
    width: "100%",
    aspectRatio: 3 / 4.2,
    backgroundColor: "#FFF",
    borderRadius: 32,
    justifyContent: "center",
    alignItems: "center",
    elevation: 4,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 20,
  },
  typeBadge: {
    position: "absolute",
    top: 12,
    left: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  badgeText: { color: "#FFF", fontSize: 7, fontWeight: "900" },
  heartBtn: {
    position: "absolute",
    top: 12,
    right: 12,
    backgroundColor: "rgba(255,255,255,0.9)",
    padding: 8,
    borderRadius: 10,
  },
  bookDetails: { marginTop: 12 },
  genreRow: { flexDirection: "row", alignItems: "center", marginBottom: 4 },
  genreText: {
    fontSize: 9,
    fontWeight: "900",
    color: "#D4AF37",
    marginLeft: 4,
  },
  bookName: { fontSize: 16, fontWeight: "900", color: "#1A1A1A" },
  posterRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
    opacity: 0.6,
  },
  posterName: {
    fontSize: 11,
    fontWeight: "700",
    color: "#6B705C",
    marginLeft: 4,
  },
  priceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#E5E0D5",
  },
  priceText: { fontSize: 16, fontWeight: "900", color: "#1A1A1A" },
  locRow: { flexDirection: "row", alignItems: "center", marginTop: 2 },
  locText: { fontSize: 8, fontWeight: "900", color: "#A5A58D", marginLeft: 2 },
  actionBtn: {
    backgroundColor: "#1A1A1A",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
  },
  actionBtnText: { color: "#FFF", fontSize: 9, fontWeight: "900" },
  emptyContainer: { alignItems: "center", padding: 60 },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: "#1A1A1A",
    marginTop: 16,
  },
  clearBtn: {
    marginTop: 20,
    backgroundColor: "#1A1A1A",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 16,
  },
  clearBtnText: { color: "#FFF", fontSize: 11, fontWeight: "900" },
  topBtn: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    marginTop: 40,
    backgroundColor: "#FFF",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E5E0D5",
  },
  topBtnText: {
    fontSize: 10,
    fontWeight: "900",
    color: "#1A1A1A",
    marginRight: 8,
  },
  footer: { alignItems: "center", marginTop: 60, opacity: 0.3 },
  footerLine: {
    width: 40,
    height: 2,
    backgroundColor: "#D4AF37",
    marginBottom: 12,
  },
  footerText: {
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 8,
    color: "#7A6B44",
  },
});
