import { Dimensions, StyleSheet } from "react-native";

const { width: SCREEN_WIDTH } = Dimensions.get("window");
const COLUMN_WIDTH = (SCREEN_WIDTH - 54) / 2;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FFFDF0" },

  bgCircleOne: {
    position: "absolute",
    top: -40,
    right: -40,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: "#5c16160A",
  },
  bgCircleTwo: {
    position: "absolute",
    bottom: "15%",
    left: -60,
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: "#D4A37310",
  },

  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  centerHeader: { alignItems: "center" },
  headerSub: {
    fontSize: 10,
    fontWeight: "900",
    color: "#D4A373",
    letterSpacing: 2.5,
    marginBottom: 2,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: "#5c1616",
    letterSpacing: -0.5,
  },
  headerBtn: {
    width: 44,
    height: 44,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#EFE8DA",
    elevation: 2,
    shadowColor: "#5c1616",
    shadowOpacity: 0.05,
    shadowRadius: 8,
  },

  tabContainer: {
    flexDirection: "row",
    backgroundColor: "#EFE8DA",
    marginHorizontal: 20,
    borderRadius: 20,
    padding: 6,
    marginVertical: 15,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    borderRadius: 14,
  },
  activeTabBtn: {
    backgroundColor: "#5c1616",
    elevation: 6,
    shadowColor: "#5c1616",
    shadowOpacity: 0.2,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  tabLabel: { fontSize: 13, fontWeight: "800", color: "#9CA3AF" },
  activeTabLabel: { color: "#FFFDF0" },

  listPadding: { paddingHorizontal: 20, paddingBottom: 60 },
  gridRow: { justifyContent: "space-between" },
  gridCard: { width: COLUMN_WIDTH, marginBottom: 20 },

  imageWrapper: {
    width: "100%",
    height: 230,
    borderRadius: 24,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#EFE8DA",
    overflow: "hidden",
    elevation: 8,
    shadowColor: "#5c1616",
    shadowOpacity: 0.08,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 8 },
  },
  bookImage: { width: "100%", height: "100%" },

  floatingHeart: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 5,
  },
  floatingRating: {
    position: "absolute",
    bottom: 12,
    left: 12,
    backgroundColor: "rgba(255, 253, 240, 0.95)",
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  ratingText: { fontSize: 11, fontWeight: "900", color: "#5c1616" },

  infoContainer: { marginTop: 14, paddingHorizontal: 4 },
  bookName: {
    fontSize: 17,
    fontWeight: "900",
    color: "#1A1A1A",
    letterSpacing: -0.3,
  },
  authorName: {
    fontSize: 13,
    color: "#9CA3AF",
    fontWeight: "700",
    marginTop: 3,
  },

  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 12,
  },
  priceValue: { fontSize: 18, fontWeight: "900", color: "#5c1616" },
  tagPill: {
    backgroundColor: "#5c161612",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  tagText: {
    color: "#5c1616",
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  arrowBtn: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#EFE8DA",
  },

  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 80,
    paddingHorizontal: 40,
  },
  emptyIconCircle: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#EFE8DA",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 24,
    elevation: 4,
    shadowColor: "#5c1616",
    shadowOpacity: 0.05,
    shadowRadius: 10,
  },
  emptyTitle: { fontSize: 22, fontWeight: "900", color: "#5c1616" },
  emptySub: {
    fontSize: 14,
    color: "#9CA3AF",
    textAlign: "center",
    marginTop: 8,
    lineHeight: 22,
    fontWeight: "500",
  },
  discoverBtn: {
    marginTop: 30,
    backgroundColor: "#5c1616",
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 20,
    elevation: 6,
    shadowColor: "#5c1616",
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
  },
  discoverText: {
    color: "#FFFDF0",
    fontWeight: "900",
    fontSize: 15,
    letterSpacing: 0.5,
  },
});
