import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");
const CARD_WIDTH = (width - 48) / 2;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FAF7F2",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    paddingVertical: 14,
    alignItems: "center",
  },
  centerHeader: { alignItems: "center" },
  headerTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#3A1F1F",
  },
  headerSub: {
    fontSize: 10,
    letterSpacing: 2,
    color: "#C69C6D",
  },
  headerBtn: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ECE7DF",
  },
  tabContainer: {
    flexDirection: "row",
    marginHorizontal: 18,
    backgroundColor: "#ECE7DF",
    borderRadius: 14,
    padding: 5,
    marginTop: 6,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderRadius: 10,
  },
  activeTabBtn: {
    backgroundColor: "#3A1F1F",
  },
  tabLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: "#7C7C7C",
  },
  activeTabLabel: {
    color: "#FFFFFF",
  },
  gridRow: {
    justifyContent: "space-between",
  },
  gridCard: {
    width: CARD_WIDTH,
    marginBottom: 18,
  },
  imageWrapper: {
    height: 210,
    borderRadius: 18,
    overflow: "hidden",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#ECE7DF",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  bookImage: {
    width: "100%",
    height: "100%",
  },
  floatingHeart: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "#FFFFFF",
    padding: 6,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#ECE7DF",
  },
  floatingRating: {
    position: "absolute",
    bottom: 10,
    left: 10,
    backgroundColor: "rgba(255,255,255,0.95)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  ratingText: {
    fontSize: 11,
    marginLeft: 4,
    fontWeight: "700",
    color: "#3A1F1F",
  },
  infoContainer: {
    marginTop: 10,
    paddingHorizontal: 2,
  },
  bookName: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1F1F1F",
  },
  authorName: {
    fontSize: 12,
    color: "#7C7C7C",
    marginTop: 2,
  },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
  },
  priceValue: {
    fontSize: 16,
    fontWeight: "800",
    color: "#3A1F1F",
  },
  tagPill: {
    backgroundColor: "#F3F0EA",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  tagText: {
    fontSize: 9,
    fontWeight: "700",
    color: "#5A3E2B",
  },
  swapTag: {
    backgroundColor: "#E6F4F1",
  },
  swapText: {
    color: "#0F766E",
  },
  arrowBtn: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#ECE7DF",
    justifyContent: "center",
    alignItems: "center",
  },
  listPadding: {
    paddingHorizontal: 18,
    paddingBottom: 40,
    marginTop: 10,
  },
  emptyContainer: {
    alignItems: "center",
    marginTop: 80,
    paddingHorizontal: 30,
  },
  emptyIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 18,
    borderWidth: 1,
    borderColor: "#ECE7DF",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 3,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#3A1F1F",
  },
  emptySub: {
    fontSize: 13,
    color: "#7C7C7C",
    textAlign: "center",
    marginTop: 6,
    lineHeight: 18,
  },
  discoverBtn: {
    marginTop: 20,
    backgroundColor: "#3A1F1F",
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 10,
  },
  discoverText: {
    color: "#FFFFFF",
    fontWeight: "700",
  },
  bgCircleOne: {
    position: "absolute",
    top: -60,
    right: -60,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: "rgba(58, 31, 31, 0.04)",
  },
  bgCircleTwo: {
    position: "absolute",
    bottom: "15%",
    left: -70,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: "rgba(198, 156, 109, 0.06)",
  },
});
