# Generated by Django 5.2.7 on 2026-01-05 19:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0003_buyermodel_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDataModel',
            fields=[
                ('book_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(default='None')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('educational_content', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('novel', 'Novel'), ('historical', 'Historical'), ('biography', 'Biography'), ('scientific', 'Scientific'), ('other', 'Other')], max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('old', 'Old')], max_length=5)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='Users.sellermodel')),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='I am using Pustakaalay 📚')),
                ('followers', models.IntegerField(default=0)),
                ('total_books', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='Users.sellermodel')),
            ],
        ),
    ]
