# Generated by Django 5.2.7 on 2025-12-23 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_buyermodel_age_buyermodel_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='I am using Pustakaalay 📚')),
                ('followers', models.IntegerField(default=0)),
                ('total_books', models.IntegerField(default=0)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='Users.sellermodel')),
            ],
        ),
    ]
