# Generated by Django 5.2.7 on 2026-04-09 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seller', '0001_initial'),
        ('Users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookbuyrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_request_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookdatamodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_books_sell', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookbuyrequest',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_request_book', to='Seller.bookdatamodel'),
        ),
        migrations.AddField(
            model_name='bookhistorymodel',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_name', to='Seller.bookdatamodel'),
        ),
        migrations.AddField(
            model_name='bookhistorymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='Users.sellermodel'),
        ),
    ]
