# Generated by Django 5.2.7 on 2026-01-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=4.91, max_digits=3),
            preserve_default=False,
        ),
    ]
