# Generated by Django 5.2.7 on 2026-01-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_alter_bookdatamodel_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdatamodel',
            name='genre',
            field=models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('sci-fi', 'Sci-fi'), ('thriller', 'Thriller')], max_length=10, null=True),
        ),
    ]
