# Generated by Django 5.2.7 on 2026-04-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdatamodel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
        ),
    ]
