# Generated by Django 5.2.7 on 2026-01-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_sellerprofile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
