# Generated by Django 5.2.7 on 2026-04-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_bookdatamodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdatamodel',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('old', 'Old')], default='New', max_length=5),
        ),
    ]
