# Generated by Django 5.2.7 on 2026-01-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_bookdatamodel_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdatamodel',
            name='educational_type',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('history', 'History'), ('technology', 'Technology'), ('mathematics', 'Mathematics'), ('medicine', 'Medicine')], max_length=15, null=True),
        ),
    ]
