# Generated by Django 5.2.7 on 2026-04-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_alter_bookdatamodel_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdatamodel',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('old', 'Old'), ('good', 'Good')], default='Good', max_length=5),
        ),
    ]
