# Generated by Django 5.2.7 on 2026-01-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_bookdatamodel_educational_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdatamodel',
            name='category',
            field=models.CharField(choices=[('novel', 'Novel'), ('historical', 'Historical'), ('biography', 'Biography'), ('scientific', 'Scientific'), ('miscellaneous', 'Miscellaneous'), ('other', 'Other')], max_length=20),
        ),
    ]
