# Generated by Django 5.2.7 on 2026-04-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0005_alter_bookdatamodel_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhistorymodel',
            name='viewed',
            field=models.BooleanField(default=True),
        ),
    ]
