# Generated by Django 5.2.7 on 2026-01-21 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0005_alter_bookdatamodel_category'),
        ('Users', '0003_buyermodel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdatamodel',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_books_sell', to='Users.sellermodel'),
        ),
    ]
