# Generated by Django 5.2.7 on 2026-04-07 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0006_alter_bookdatamodel_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdatamodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
