# Generated by Django 5.2.7 on 2026-04-07 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0007_bookdatamodel_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdatamodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookdatamodel',
            name='saved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookdatamodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BookHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('saved', models.BooleanField(default=False)),
                ('viewed', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_name', to='Seller.bookdatamodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
