# Generated by Django 5.2.7 on 2026-04-08 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0009_bookbuyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookbuyrequest',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
