# Generated by Django 5.2.7 on 2026-04-08 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0010_bookbuyrequest_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookbuyrequest',
            name='id',
        ),
        migrations.AddField(
            model_name='bookbuyrequest',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
