# Generated by Django 5.2.7 on 2026-04-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0011_remove_bookbuyrequest_id_bookbuyrequest_request_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookbuyrequest',
            old_name='request_id',
            new_name='buy_request_id',
        ),
    ]
