# Generated by Django 5.2.7 on 2025-12-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_buyermodel_age_buyermodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyermodel',
            name='city',
            field=models.CharField(default='Indore', max_length=100),
            preserve_default=False,
        ),
    ]
