import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FFFDF0" },
  safeArea: { flex: 1 },

  bgCircleTop: {
    position: "absolute",
    top: -50,
    right: -50,
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: "rgba(92, 22, 22, 0.03)",
  },
  bgCircleBottom: {
    position: "absolute",
    bottom: -50,
    left: -50,
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: "rgba(92, 22, 22, 0.03)",
  },

  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  headerBtn: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#EFE8DA",
    elevation: 2,
    shadowColor: "#5c1616",
    shadowOpacity: 0.05,
    shadowRadius: 8,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: "#5c1616",
    letterSpacing: -0.5,
  },
  headerSpacer: { width: 46 },

  scrollPadding: { paddingHorizontal: 20, paddingBottom: 60, paddingTop: 15 },

  heroSection: { alignItems: "center", marginBottom: 35 },
  heroIconWrapper: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: "rgba(92, 22, 22, 0.05)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  heroIconInner: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#EFE8DA",
    elevation: 6,
    shadowColor: "#5c1616",
    shadowOpacity: 0.08,
    shadowRadius: 15,
  },
  heroTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: "#1A1A1A",
    marginBottom: 8,
  },
  heroText: {
    fontSize: 14,
    color: "#9CA3AF",
    fontWeight: "500",
    textAlign: "center",
    paddingHorizontal: 30,
    lineHeight: 22,
  },

  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "#EFE8DA",
    ...Platform.select({
      ios: {
        shadowColor: "#5c1616",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.04,
        shadowRadius: 16,
      },
      android: { elevation: 3 },
    }),
  },

  sectionTitle: {
    fontSize: 13,
    fontWeight: "900",
    color: "#9CA3AF",
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginVertical: 10,
    marginLeft: 8,
  },

  row: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 8,
  },
  iconBox: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "#F8FAFC",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  rowText: { flex: 1, paddingRight: 15 },
  rowTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: "#1A1A1A",
    marginBottom: 4,
  },
  rowSubtitle: { fontSize: 13, color: "#94A3B8", fontWeight: "500" },
  chevronBox: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "#F8FAFC",
    justifyContent: "center",
    alignItems: "center",
  },

  divider: {
    height: 1,
    backgroundColor: "#F1F5F9",
    marginLeft: 68,
    marginVertical: 4,
  },

  dangerCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF1F2",
    borderRadius: 24,
    padding: 20,
    marginTop: 10,
    marginBottom: 30,
    borderWidth: 1,
    borderColor: "#FECDD3",
  },
  dangerIconBox: {
    width: 50,
    height: 50,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
    elevation: 2,
    shadowColor: "#EF4444",
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  dangerTextWrap: { flex: 1 },
  dangerTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: "#EF4444",
    marginBottom: 4,
  },
  dangerSubtitle: { fontSize: 13, color: "#F87171", fontWeight: "600" },

  versionText: {
    textAlign: "center",
    fontSize: 13,
    color: "#CBD5E1",
    fontWeight: "800",
    marginBottom: 20,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(26, 26, 26, 0.6)",
    justifyContent: "flex-end",
  },
  modalSheet: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: Platform.OS === "ios" ? 40 : 24,
    width: "100%",
  },
  dragHandle: {
    width: 40,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#E2E8F0",
    alignSelf: "center",
    marginBottom: 15,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: "#1A1A1A",
    letterSpacing: -0.5,
  },
  closeBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F8FAFC",
    justifyContent: "center",
    alignItems: "center",
  },
  modalSubtitle: {
    fontSize: 14,
    color: "#64748B",
    fontWeight: "500",
    marginBottom: 25,
    lineHeight: 22,
  },

  inputGroup: { marginBottom: 18 },
  inputLabel: {
    fontSize: 13,
    fontWeight: "800",
    color: "#64748B",
    marginBottom: 8,
    marginLeft: 4,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    paddingHorizontal: 16,
    height: 60,
  },
  inputIcon: { marginRight: 12 },
  input: { flex: 1, fontSize: 16, fontWeight: "600", color: "#1A1A1A" },
  forgotPassBtn: { alignSelf: "flex-end", marginTop: 8, marginRight: 4 },
  forgotPassText: { fontSize: 13, fontWeight: "700", color: "#5c1616" },

  primaryBtn: {
    backgroundColor: "#1A1A1A",
    borderRadius: 20,
    height: 60,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  primaryBtnText: { color: "#FFFFFF", fontSize: 16, fontWeight: "900" },

  legalBlock: {
    backgroundColor: "#F8FAFC",
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#F1F5F9",
  },
  legalSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  legalBadge: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "#5c1616",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  legalBadgeText: { color: "#FFFFFF", fontSize: 12, fontWeight: "900" },
  legalSectionTitle: { fontSize: 17, fontWeight: "900", color: "#1A1A1A" },
  legalText: {
    fontSize: 15,
    color: "#64748B",
    lineHeight: 24,
    fontWeight: "500",
  },
});