# Generated by Django 5.2.7 on 2026-04-09 18:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookForSellBuyer',
            fields=[
                ('book_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(default='No Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('novel', 'Novel'), ('historical', 'Historical'), ('biography', 'Biography'), ('scientific', 'Scientific'), ('miscellaneous', 'Miscellaneous'), ('other', 'Other')], max_length=20)),
                ('genre', models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('sci-fi', 'Sci-fi'), ('thriller', 'Thriller')], max_length=10, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('old', 'Old')], default='fair', max_length=10)),
                ('likes', models.IntegerField(default=0)),
                ('saved', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='I love pustak 📙')),
                ('followers', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EbookHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_page_number', models.IntegerField(default=1)),
                ('saved', models.BooleanField(default=False)),
                ('liked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EbookModel',
            fields=[
                ('ebook_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(default='No Description')),
                ('category', models.CharField(choices=[('novel', 'Novel'), ('historical', 'Historical'), ('biography', 'Biography'), ('scientific', 'Scientific'), ('miscellaneous', 'Miscellaneous'), ('other', 'Other')], max_length=20)),
                ('genre', models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('sci-fi', 'Sci-fi'), ('thriller', 'Thriller')], max_length=10, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('saved', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeBookModel',
            fields=[
                ('book_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('novel', 'Novel'), ('historical', 'Historical'), ('biography', 'Biography'), ('scientific', 'Scientific'), ('miscellaneous', 'Miscellaneous'), ('other', 'Other')], max_length=20)),
                ('genre', models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('sci-fi', 'Sci-fi'), ('thriller', 'Thriller')], max_length=10, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('old', 'Old')], default='fair', max_length=10)),
                ('desired_category', models.CharField(choices=[('novel', 'Novel'), ('historical', 'Historical'), ('biography', 'Biography'), ('scientific', 'Scientific'), ('miscellaneous', 'Miscellaneous'), ('other', 'Other')], max_length=20)),
                ('desired_genre', models.CharField(choices=[('fiction', 'Fiction'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('sci-fi', 'Sci-fi'), ('thriller', 'Thriller')], max_length=10)),
                ('wanted_condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('old', 'Old')], default='fair', max_length=10)),
                ('description', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('saved', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TradeHistoryModel',
            fields=[
                ('trade_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('trade_type', models.CharField(choices=[('sell', 'Sell'), ('exchange', 'Exchange'), ('bought', 'Bought')], max_length=10)),
            ],
        ),
    ]
