# Generated by Django 5.2.7 on 2026-01-21 18:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
        ('Users', '0003_buyermodel_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookForSellBuyer',
            fields=[
                ('book_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(default='None')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('novel', 'Novel'), ('historical', 'Historical'), ('biography', 'Biography'), ('scientific', 'Scientific'), ('miscellaneous', 'Miscellaneous'), ('other', 'Other')], max_length=20)),
                ('genre', models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('sci-fi', 'Sci-fi'), ('thriller', 'Thriller')], max_length=10, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_books_sell', to='Users.buyermodel')),
            ],
        ),
    ]
