# Generated by Django 5.2.7 on 2026-04-09 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Buyer', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookforsellbuyer',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_books_sell', to='Users.buyermodel'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='Users.buyermodel'),
        ),
        migrations.AddField(
            model_name='ebookhistory',
            name='buyer_seen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyerebook_buyer', to='Users.buyermodel'),
        ),
        migrations.AddField(
            model_name='ebookmodel',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_ebook', to='Users.buyermodel'),
        ),
        migrations.AddField(
            model_name='ebookhistory',
            name='ebook_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebook', to='Buyer.ebookmodel'),
        ),
        migrations.AddField(
            model_name='exchangebookmodel',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_book_buyer', to='Users.buyermodel'),
        ),
        migrations.AddField(
            model_name='tradehistorymodel',
            name='trade_buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_buyer', to='Users.buyermodel'),
        ),
        migrations.AddField(
            model_name='tradehistorymodel',
            name='trade_exchange_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_exchange_book', to='Buyer.exchangebookmodel'),
        ),
        migrations.AddField(
            model_name='tradehistorymodel',
            name='trade_sell_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_sell_book', to='Buyer.bookforsellbuyer'),
        ),
        migrations.AddField(
            model_name='tradehistorymodel',
            name='trade_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_seller', to='Users.buyermodel'),
        ),
    ]
