# Generated by Django 5.2.7 on 2026-04-09 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0002_initial'),
        ('Seller', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistorymodel',
            name='trade_sell_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_sell_book', to='Seller.bookdatamodel'),
        ),
        migrations.DeleteModel(
            name='BookForSellBuyer',
        ),
    ]
