# Generated by Django 5.2.7 on 2026-04-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_alter_tradehistorymodel_trade_sell_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebookmodel',
            name='score',
        ),
    ]
