# Generated by Django 5.2.7 on 2026-03-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_alter_bookforsellbuyer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebookmodel',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
