# Generated by Django 5.2.7 on 2026-04-16 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_remove_ebookmodel_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebookmodel',
            name='date',
        ),
        migrations.AddField(
            model_name='ebookmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
