# Generated by Django 5.2.7 on 2026-03-26 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_alter_ebookmodel_date'),
        ('Users', '0003_buyermodel_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_page_number', models.IntegerField(default=1)),
                ('saved', models.BooleanField(default=False)),
                ('liked', models.BooleanField(default=False)),
                ('buyer_seen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyerebook_buyer', to='Users.buyermodel')),
                ('ebook_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebook', to='Buyer.ebookmodel')),
            ],
        ),
    ]
