# Generated by Django 5.2.7 on 2026-03-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0005_ebookhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookforsellbuyer',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('old', 'Old')], default='fair', max_length=10),
        ),
    ]
