# Generated by Django 5.2.7 on 2026-04-16 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0005_remove_ebookmodel_date_ebookmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangebookmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
