# Generated by Django 5.2.7 on 2026-03-28 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0006_bookforsellbuyer_condition'),
        ('Users', '0003_buyermodel_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeBookModel',
            fields=[
                ('book_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('novel', 'Novel'), ('historical', 'Historical'), ('biography', 'Biography'), ('scientific', 'Scientific'), ('miscellaneous', 'Miscellaneous'), ('other', 'Other')], max_length=20)),
                ('genre', models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('sci-fi', 'Sci-fi'), ('thriller', 'Thriller')], max_length=10, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('old', 'Old')], default='fair', max_length=10)),
                ('desired_genre', models.CharField(choices=[('fiction', 'Fiction'), ('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('sci-fi', 'Sci-fi'), ('thriller', 'Thriller')], max_length=10)),
                ('wanted_condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('old', 'Old')], default='fair', max_length=10)),
                ('description', models.TextField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_book_buyer', to='Users.buyermodel')),
            ],
        ),
    ]
