# Generated by Django 5.2.7 on 2026-04-16 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0006_exchangebookmodel_created_at'),
        ('Seller', '0005_alter_bookdatamodel_condition'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeBookHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('saved', models.BooleanField(default=False)),
                ('viewed', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_book_name', to='Seller.bookdatamodel')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_history_user', to='Users.buyermodel')),
            ],
        ),
    ]
