# Generated by Django 5.2.7 on 2026-03-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0007_exchangebookmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangebookmodel',
            name='desired_category',
            field=models.CharField(choices=[('novel', 'Novel'), ('historical', 'Historical'), ('biography', 'Biography'), ('scientific', 'Scientific'), ('miscellaneous', 'Miscellaneous'), ('other', 'Other')], default='novel', max_length=20),
            preserve_default=False,
        ),
    ]
