# Generated by Django 5.2.7 on 2026-04-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0007_exchangebookhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangebookmodel',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
