# Generated by Django 5.2.7 on 2026-04-16 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0008_exchangebookmodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebookmodel',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
