# Generated by Django 5.2.7 on 2026-03-29 07:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0008_exchangebookmodel_desired_category'),
        ('Users', '0003_buyermodel_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeHistoryModel',
            fields=[
                ('trade_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('trade_type', models.CharField(choices=[('sell', 'Sell'), ('exchange', 'Exchange'), ('bought', 'Bought')], max_length=10)),
                ('trade_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_book', to='Buyer.exchangebookmodel')),
                ('trade_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_buyer', to='Users.buyermodel')),
                ('trade_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_seller', to='Users.buyermodel')),
            ],
        ),
    ]
