# Generated by Django 5.2.7 on 2026-03-29 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0009_tradehistorymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradehistorymodel',
            name='trade_book',
        ),
        migrations.AddField(
            model_name='tradehistorymodel',
            name='trade_exchange_book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='trade_exchange_book', to='Buyer.exchangebookmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradehistorymodel',
            name='trade_sell_book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='trade_sell_book', to='Buyer.bookforsellbuyer'),
            preserve_default=False,
        ),
    ]
