# Generated by Django 5.2.7 on 2026-04-16 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0009_ebookmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangebookhistory',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_book_name', to='Buyer.exchangebookmodel'),
        ),
    ]
