# Generated by Django 5.2.7 on 2026-03-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0010_remove_tradehistorymodel_trade_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookforsellbuyer',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookforsellbuyer',
            name='saved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ebookmodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ebookmodel',
            name='saved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchangebookmodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchangebookmodel',
            name='saved',
            field=models.IntegerField(default=0),
        ),
    ]
