# Generated by Django 5.2.7 on 2026-06-14 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0010_alter_exchangebookhistory_book'),
        ('Seller', '0006_alter_bookhistorymodel_viewed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangebookhistory',
            name='viewed',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BuyBookRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_amount', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_request_book_buyer', to='Seller.bookdatamodel')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_book_requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
