# Generated by Django 5.2.7 on 2026-03-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0011_bookforsellbuyer_likes_bookforsellbuyer_saved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookforsellbuyer',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchangebookmodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
