# Generated by Django 5.2.7 on 2026-06-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0012_buybookrequest_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='buybookrequest',
            name='date',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
