# Generated by Django 5.2.7 on 2026-03-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0012_bookforsellbuyer_views_exchangebookmodel_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebookmodel',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
