# Generated by Django 5.2.7 on 2026-03-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0013_ebookmodel_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebookmodel',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
