# Generated by Django 5.2.7 on 2026-04-01 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0015_alter_tradehistorymodel_trade_buyer_and_more'),
        ('Users', '0003_buyermodel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistorymodel',
            name='trade_buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_buyer', to='Users.buyermodel'),
        ),
        migrations.AlterField(
            model_name='tradehistorymodel',
            name='trade_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_seller', to='Users.buyermodel'),
        ),
    ]
