# Generated by Django 5.2.7 on 2026-04-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0016_alter_tradehistorymodel_trade_buyer_and_more'),
        ('Users', '0003_buyermodel_city'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tradehistorymodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('trade_buyer__isnull', False), ('trade_seller__isnull', True)), models.Q(('trade_buyer__isnull', True), ('trade_seller__isnull', False)), _connector='OR'), name='only_one_of_buyer_or_seller'),
        ),
    ]
