# Generated by Django 5.2.7 on 2026-04-01 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0017_tradehistorymodel_only_one_of_buyer_or_seller'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tradehistorymodel',
            name='only_one_of_buyer_or_seller',
        ),
    ]
