# Generated by Django 5.2.7 on 2026-04-02 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0018_remove_tradehistorymodel_only_one_of_buyer_or_seller'),
        ('Users', '0003_buyermodel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistorymodel',
            name='trade_buyer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trade_buyer', to='Users.buyermodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tradehistorymodel',
            name='trade_exchange_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_exchange_book', to='Buyer.exchangebookmodel'),
        ),
        migrations.AlterField(
            model_name='tradehistorymodel',
            name='trade_sell_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_sell_book', to='Buyer.bookforsellbuyer'),
        ),
        migrations.AlterField(
            model_name='tradehistorymodel',
            name='trade_seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trade_seller', to='Users.buyermodel'),
            preserve_default=False,
        ),
    ]
