import { Dimensions, StyleSheet } from "react-native";

const { width: SCREEN_WIDTH } = Dimensions.get("window");
const scale = (size: number) => (SCREEN_WIDTH / 375) * size;
const moderateScale = (size: number, factor = 0.5) =>
  size + (scale(size) - size) * factor;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FCF9F1" },
  scrollContent: { paddingBottom: moderateScale(40) },
  navBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: moderateScale(20),
  },
  backButton: { flexDirection: "row", alignItems: "center" },
  backLabel: {
    fontSize: moderateScale(11),
    fontWeight: "900",
    color: "#6B705C",
    marginLeft: moderateScale(8),
    letterSpacing: 1,
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF",
    paddingHorizontal: moderateScale(10),
    paddingVertical: moderateScale(5),
    borderRadius: moderateScale(12),
    borderWidth: 1,
    borderColor: "#F4F1EA",
  },
  badgeText: {
    fontSize: moderateScale(9),
    fontWeight: "900",
    color: "#D4AF37",
    marginLeft: moderateScale(5),
  },
  hero: {
    paddingHorizontal: moderateScale(24),
    marginBottom: moderateScale(20),
  },
  heroTitle: {
    fontSize: moderateScale(32),
    fontWeight: "900",
    color: "#1A1A1A",
    letterSpacing: -1,
  },
  heroSub: {
    fontSize: moderateScale(14),
    color: "#9C8C64",
    marginTop: moderateScale(4),
  },
  formCard: {
    backgroundColor: "#FFF",
    marginHorizontal: moderateScale(16),
    borderRadius: moderateScale(32),
    padding: moderateScale(20),
    elevation: 4,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
  },
  inputGroup: { marginBottom: moderateScale(18) },
  labelRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: moderateScale(8),
  },
  labelText: {
    fontSize: moderateScale(10),
    fontWeight: "900",
    color: "#1A1A1A",
    marginLeft: moderateScale(8),
    letterSpacing: 1.5,
  },
  textInput: {
    backgroundColor: "#FCFBFA",
    borderRadius: moderateScale(14),
    padding: moderateScale(14),
    fontSize: moderateScale(15),
    fontWeight: "600",
    color: "#1A1A1A",
    borderWidth: 1,
    borderColor: "#F0EEE9",
  },
  textArea: {
    backgroundColor: "#FCFBFA",
    borderRadius: moderateScale(14),
    padding: moderateScale(14),
    fontSize: moderateScale(15),
    fontWeight: "600",
    color: "#1A1A1A",
    borderWidth: 1,
    borderColor: "#F0EEE9",
    minHeight: moderateScale(100),
    textAlignVertical: "top",
  },
  uploadBox: {
    height: moderateScale(100),
    borderStyle: "dashed",
    borderWidth: 2,
    borderColor: "#E5E0D5",
    borderRadius: moderateScale(16),
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FCFBFA",
  },
  uploadText: {
    fontSize: moderateScale(11),
    fontWeight: "800",
    color: "#A5A58D",
    marginTop: moderateScale(8),
  },
  selectorTrigger: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#FCFBFA",
    borderRadius: moderateScale(14),
    padding: moderateScale(14),
    borderWidth: 1,
    borderColor: "#F0EEE9",
  },
  selectorValue: {
    fontSize: moderateScale(15),
    fontWeight: "700",
    color: "#1A1A1A",
  },
  row: { flexDirection: "row" },
  toggleCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#F8F5E9",
    padding: moderateScale(16),
    borderRadius: moderateScale(18),
    marginBottom: moderateScale(18),
  },
  toggleInfo: { flexDirection: "row", alignItems: "center" },
  toggleMain: {
    fontSize: moderateScale(13),
    fontWeight: "800",
    color: "#1A1A1A",
  },
  toggleSub: { fontSize: moderateScale(10), color: "#9C8C64" },
  submitBtn: {
    backgroundColor: "#1A1A1A",
    height: moderateScale(64),
    borderRadius: moderateScale(32),
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: moderateScale(25),
    marginTop: moderateScale(10),
  },
  submitText: {
    color: "#FFF",
    fontSize: moderateScale(14),
    fontWeight: "900",
    letterSpacing: 1.5,
  },
  submitCircle: {
    width: moderateScale(44),
    height: moderateScale(44),
    borderRadius: moderateScale(22),
    backgroundColor: "#D4AF37",
    justifyContent: "center",
    alignItems: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#FFF",
    borderTopLeftRadius: moderateScale(32),
    borderTopRightRadius: moderateScale(32),
    padding: moderateScale(24),
    paddingBottom: moderateScale(40),
  },
  modalIndicator: {
    width: moderateScale(40),
    height: moderateScale(4),
    backgroundColor: "#E5E0D5",
    borderRadius: moderateScale(2),
    alignSelf: "center",
    marginBottom: moderateScale(20),
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: moderateScale(15),
  },
  modalTitle: {
    fontSize: moderateScale(18),
    fontWeight: "900",
    color: "#1A1A1A",
  },
  closeBtn: { padding: moderateScale(5) },
  optionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: moderateScale(18),
    borderBottomWidth: 1,
    borderBottomColor: "#F4F1EA",
  },
  optionRowActive: { borderBottomColor: "#1A1A1A" },
  optionText: {
    fontSize: moderateScale(16),
    fontWeight: "600",
    color: "#6B705C",
  },
  optionTextActive: { color: "#1A1A1A", fontWeight: "800" },
  footer: { alignItems: "center", marginTop: moderateScale(40), opacity: 0.3 },
  footerText: {
    fontSize: moderateScale(9),
    fontWeight: "900",
    color: "#1A1A1A",
    marginTop: moderateScale(10),
    letterSpacing: 2,
  },
});
