import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");
const cardWidth = (width - 64) / 2;

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#FCF9F1" },
  header: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 20,
    backgroundColor: "#FCF9F1",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.05)",
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  kicker: {
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 3,
    color: "#D4AF37",
  },
  mainTitle: {
    fontSize: 28,
    fontWeight: "900",
    color: "#1A1A1A",
    letterSpacing: -0.5,
  },
  iconButton: {
    width: 44,
    height: 44,
    backgroundColor: "white",
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E5E0D5",
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E5E0D5",
    paddingHorizontal: 16,
    height: 52,
  },
  input: {
    flex: 1,
    marginLeft: 10,
    fontSize: 15,
    color: "#1A1A1A",
    fontWeight: "600",
  },
  scrollPadding: { paddingHorizontal: 24, paddingVertical: 24 },
  metaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  countContainer: { flexDirection: "row", alignItems: "center" },
  accentLine: {
    width: 3,
    height: 14,
    backgroundColor: "#721C24",
    borderRadius: 2,
    marginRight: 8,
  },
  countText: { fontSize: 10, fontWeight: "800", color: "#6B705C" },
  locationContainer: {
    flexDirection: "row",
    alignItems: "center",
    opacity: 0.5,
  },
  locationText: {
    fontSize: 10,
    fontWeight: "900",
    marginLeft: 4,
    color: "#1A1A1A",
  },
  bookGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  bookCard: { width: cardWidth, marginBottom: 28 },
  imagePlaceholder: {
    width: "100%",
    aspectRatio: 0.75,
    backgroundColor: "white",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "#E5E0D5",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  badge: {
    position: "absolute",
    top: 10,
    left: 10,
    backgroundColor: "rgba(26,26,26,0.9)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  badgeText: { color: "white", fontSize: 8, fontWeight: "900" },
  heartButton: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "white",
    width: 32,
    height: 32,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  externalLink: {
    position: "absolute",
    bottom: 10,
    right: 10,
    backgroundColor: "#FCF9F1",
    width: 28,
    height: 28,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E5E0D5",
  },
  contentPadding: { marginTop: 12 },
  genreTag: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#FCF9F1",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "rgba(212,175,55,0.15)",
    marginBottom: 6,
  },
  genreText: {
    fontSize: 8,
    fontWeight: "900",
    color: "#D4AF37",
    marginLeft: 4,
  },
  bookName: {
    fontSize: 15,
    fontWeight: "800",
    color: "#1A1A1A",
    marginBottom: 2,
  },
  sellerRow: { flexDirection: "row", alignItems: "center", opacity: 0.6 },
  sellerHandle: {
    fontSize: 11,
    fontWeight: "600",
    color: "#6B705C",
    marginLeft: 4,
  },
  footerRow: {
    marginTop: 12,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.05)",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  priceTag: { fontSize: 16, fontWeight: "900", color: "#1A1A1A" },
  buyButton: {
    backgroundColor: "#1A1A1A",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
  },
  buyText: { color: "white", fontSize: 9, fontWeight: "900", marginRight: 4 },
  footer: { alignItems: "center", marginTop: 40, paddingBottom: 60 },
  footerLabel: {
    fontSize: 10,
    fontWeight: "900",
    color: "#A5A58D",
    letterSpacing: 2,
  },
  topBtn: {
    marginTop: 20,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E0D5",
  },
  topBtnText: { fontSize: 10, fontWeight: "900", marginRight: 8 },
  emptyContainer: { alignItems: "center", paddingVertical: 80 },
  emptyText: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1A1A1A",
    marginTop: 16,
  },
  resetBtn: {
    marginTop: 20,
    backgroundColor: "#1A1A1A",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
  },
  resetText: { color: "white", fontSize: 10, fontWeight: "900" },
});
