import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");

const s = (size: number) => {
  const scale = width / 375;
  return Math.min(size * scale, size * 1.15);
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FCF9F1" },
  meshContainer: { ...StyleSheet.absoluteFillObject, overflow: "hidden" },
  blob1: {
    position: "absolute",
    width: s(400),
    height: s(400),
    borderRadius: 200,
    backgroundColor: "#F5E6CC",
    top: -s(100),
    right: -s(80),
    opacity: 0.4,
  },
  blob2: {
    position: "absolute",
    width: s(300),
    height: s(300),
    borderRadius: 150,
    backgroundColor: "#E8D8C3",
    top: "40%",
    left: -s(100),
    opacity: 0.3,
  },
  scrollContent: {
    paddingHorizontal: s(20),
    paddingTop: s(15),
    paddingBottom: s(30),
  },

  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: s(25),
  },
  userInfo: { flexDirection: "row", alignItems: "center" },
  avatarWrapper: { position: "relative" },
  avatar: {
    width: s(48),
    height: s(48),
    backgroundColor: "#1A1A1A",
    borderRadius: s(12),
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "white",
  },
  onlineBadge: {
    position: "absolute",
    bottom: -1,
    right: -1,
    backgroundColor: "#D4AF37",
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "#FCF9F1",
    padding: 1,
  },
  userRole: {
    fontSize: s(9),
    fontWeight: "800",
    color: "#6B705C",
    letterSpacing: 1,
  },
  userName: { fontSize: s(18), fontWeight: "900", color: "#1A1A1A" },
  iconBtn: {
    width: s(40),
    height: s(40),
    backgroundColor: "white",
    borderRadius: s(12),
    borderWidth: 1,
    borderColor: "#E5E0D5",
    justifyContent: "center",
    alignItems: "center",
  },
  notifDot: {
    position: "absolute",
    top: s(8),
    right: s(8),
    width: s(7),
    height: s(7),
    backgroundColor: "#721C24",
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: "white",
  },

  walletCard: {
    backgroundColor: "#1A1A1A",
    borderRadius: s(24),
    padding: s(20),
    marginBottom: s(25),
    overflow: "hidden",
  },
  walletDecor: { position: "absolute", right: -s(15), top: -s(15) },
  walletInfo: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  walletLabel: {
    color: "rgba(255,255,255,0.4)",
    fontSize: s(9),
    fontWeight: "700",
    letterSpacing: 1,
    marginBottom: 2,
  },
  walletAmount: { color: "#D4AF37", fontSize: s(24), fontWeight: "900" },
  ratingBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.1)",
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 6,
  },
  ratingText: {
    color: "white",
    fontSize: s(10),
    fontWeight: "800",
    marginLeft: 3,
  },
  ratingSub: {
    color: "rgba(255,255,255,0.3)",
    fontSize: s(8),
    fontWeight: "700",
    marginTop: 2,
  },

  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: s(16),
    paddingHorizontal: s(12),
    height: s(48),
    borderWidth: 1,
    borderColor: "#E5E0D5",
    marginBottom: s(30),
  },
  searchInput: {
    flex: 1,
    marginLeft: s(8),
    fontSize: s(14),
    fontWeight: "600",
    color: "#1A1A1A",
  },
  scanBtn: {
    width: s(28),
    height: s(28),
    backgroundColor: "#FCF9F1",
    borderRadius: 6,
    justifyContent: "center",
    alignItems: "center",
  },

  actionHub: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: s(35),
  },
  actionCard: {
    width: "48%",
    backgroundColor: "white",
    borderRadius: s(24),
    paddingVertical: s(20),
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E5E0D5",
  },
  iconBoxDark: {
    width: s(44),
    height: s(44),
    backgroundColor: "#1A1A1A",
    borderRadius: s(14),
    justifyContent: "center",
    alignItems: "center",
    marginBottom: s(8),
  },
  iconBoxLight: {
    width: s(44),
    height: s(44),
    backgroundColor: "#F4F2EE",
    borderRadius: s(14),
    justifyContent: "center",
    alignItems: "center",
    marginBottom: s(8),
  },
  actionTitle: { fontSize: s(15), fontWeight: "800", color: "#1A1A1A" },
  actionHint: {
    fontSize: s(8),
    fontWeight: "700",
    color: "#A5A58D",
    marginTop: 2,
  },

  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: s(15),
  },
  rowAlignCenter: { flexDirection: "row", alignItems: "center" },
  rowSpaceBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  indicator: { width: 3, height: s(18), borderRadius: 2, marginRight: s(8) },
  sectionTitle: { fontSize: s(15), fontWeight: "900", color: "#1A1A1A" },
  badgeLabel: {
    backgroundColor: "rgba(114,28,36,0.06)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
  },
  badgeText: { fontSize: s(9), fontWeight: "800", color: "#721C24" },

  requestCard: {
    backgroundColor: "white",
    borderRadius: s(24),
    marginBottom: s(12),
    flexDirection: "row",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E5E0D5",
  },
  accentBar: { width: 4, backgroundColor: "#721C24" },
  requestMain: { flex: 1, padding: s(15) },
  requestIcon: {
    width: s(42),
    height: s(42),
    backgroundColor: "#FDFDFB",
    borderRadius: s(10),
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E5E0D5",
  },
  itemTitle: { fontSize: s(14), fontWeight: "800", color: "#1A1A1A" },
  subText: { fontSize: s(11), color: "#6B705C", fontWeight: "600" },
  priceHighlight: { fontSize: s(15), fontWeight: "900", color: "#721C24" },
  timeText: { fontSize: s(8), color: "#A5A58D", fontWeight: "700" },
  requestButtons: { flexDirection: "row", marginTop: s(12), gap: s(8) },
  primaryBtn: {
    flex: 1,
    backgroundColor: "#1A1A1A",
    height: s(36),
    borderRadius: s(10),
    justifyContent: "center",
    alignItems: "center",
  },
  primaryBtnText: { color: "white", fontSize: s(9), fontWeight: "800" },
  secondaryBtn: {
    width: s(36),
    height: s(36),
    backgroundColor: "#F4F2EE",
    borderRadius: s(10),
    justifyContent: "center",
    alignItems: "center",
  },

  dashedBtn: {
    width: "100%",
    height: s(48),
    borderStyle: "dashed",
    borderWidth: 1.5,
    borderColor: "#E5E0D5",
    borderRadius: s(15),
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    marginTop: 5,
  },
  dashedBtnText: {
    fontSize: s(10),
    fontWeight: "800",
    color: "#6B705C",
    letterSpacing: 0.5,
  },

  radarContainer: {
    backgroundColor: "#F4F2EE",
    marginHorizontal: -s(20),
    paddingHorizontal: s(20),
    paddingVertical: s(25),
    borderTopLeftRadius: s(35),
    borderTopRightRadius: s(35),
    marginTop: s(25),
  },
  radarCard: {
    backgroundColor: "white",
    borderRadius: s(20),
    padding: s(12),
    flexDirection: "row",
    marginBottom: s(12),
  },
  bookThumb: {
    width: s(55),
    height: s(75),
    backgroundColor: "#FCF9F1",
    borderRadius: s(10),
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  premiumLabel: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    backgroundColor: "#D4AF37",
    paddingVertical: 2,
  },
  premiumText: {
    color: "white",
    fontSize: s(6),
    fontWeight: "900",
    textAlign: "center",
  },
  priceDark: { fontSize: s(15), fontWeight: "900", color: "#1A1A1A" },
  locText: {
    fontSize: s(9),
    fontWeight: "700",
    color: "#6B705C",
    marginLeft: 4,
  },
  buyBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1A1A1A",
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    gap: 4,
  },
  buyBtnText: { color: "white", fontSize: s(9), fontWeight: "800" },
  miniBtn: {
    backgroundColor: "white",
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 10,
  },
  miniBtnText: { fontSize: s(9), fontWeight: "800", color: "#D4AF37" },

  inventoryContainer: { marginTop: s(30) },
  inventoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  gridCard: {
    width: "48%",
    backgroundColor: "white",
    borderRadius: s(20),
    padding: s(12),
    marginBottom: s(15),
    borderWidth: 1,
    borderColor: "#E5E0D5",
  },
  gridImgPlaceholder: {
    height: s(110),
    backgroundColor: "#FDFDFB",
    borderRadius: s(15),
    justifyContent: "center",
    alignItems: "center",
    marginBottom: s(10),
  },
  gridIconFloating: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: "white",
    padding: 4,
    borderRadius: 6,
  },
  gridTitle: {
    fontSize: s(13),
    fontWeight: "800",
    color: "#1A1A1A",
    marginBottom: 4,
  },
  gridPrice: { fontSize: s(14), fontWeight: "900", color: "#1A1A1A" },
  gridStats: {
    fontSize: s(9),
    fontWeight: "700",
    color: "#A5A58D",
    marginLeft: 3,
  },
  miniBtnGray: {
    backgroundColor: "#F4F2EE",
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 10,
  },
  miniBtnTextGray: { fontSize: s(9), fontWeight: "800", color: "#A5A58D" },

  growthCard: {
    backgroundColor: "#1A1A1A",
    borderRadius: s(30),
    padding: s(25),
    marginTop: s(20),
    overflow: "hidden",
  },
  sparkle: { position: "absolute", right: -s(10), top: -s(10) },
  growthLabel: {
    color: "#D4AF37",
    fontSize: s(9),
    fontWeight: "800",
    letterSpacing: 2,
    marginBottom: s(5),
  },
  growthTitle: {
    color: "white",
    fontSize: s(24),
    fontWeight: "900",
    lineHeight: s(26),
    marginBottom: s(15),
  },
  hubBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#D4AF37",
    borderRadius: s(12),
    paddingLeft: 12,
    paddingRight: 4,
    height: s(40),
    width: s(130),
  },
  hubBtnText: { fontWeight: "800", fontSize: s(10) },
  hubArrow: {
    width: s(32),
    height: s(32),
    backgroundColor: "black",
    borderRadius: s(10),
    justifyContent: "center",
    alignItems: "center",
  },

  footer: { paddingVertical: s(40), alignItems: "center" },
  footerLogo: {
    fontSize: s(12),
    fontWeight: "800",
    color: "#7A6B44",
    letterSpacing: 4,
    opacity: 0.6,
  },
  footerTag: {
    fontSize: s(8),
    fontWeight: "700",
    color: "#A5A58D",
    marginTop: s(4),
    opacity: 0.6,
  },
});