import { Dimensions, Platform, StyleSheet } from "react-native";

const { height: SCREEN_HEIGHT, width: SCREEN_WIDTH } = Dimensions.get("window");

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(15, 23, 42, 0.6)",
  },
  backdrop: { ...StyleSheet.absoluteFillObject },
  bottomSheet: {
    backgroundColor: "#FFFDF0",
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    maxHeight: SCREEN_HEIGHT * 0.9,
    width: "100%",
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -12 },
        shadowOpacity: 0.15,
        shadowRadius: 16,
      },
      android: { elevation: 24 },
    }),
  },
  header: {
    paddingTop: 14,
    alignItems: "center",
  },
  dragHandle: {
    width: 38,
    height: 5,
    backgroundColor: "#E2E8F0",
    borderRadius: 10,
    marginBottom: 10,
  },
  headerActionRow: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    alignItems: "center",
  },
  ratingBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFBEB",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#FEF3C7",
  },
  ratingText: {
    fontSize: 13,
    fontWeight: "900",
    color: "#D97706",
    marginLeft: 4,
  },
  closeButton: {
    backgroundColor: "#F1F5F9",
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  scrollContent: {
    paddingBottom: 160,
  },
  imageSection: {
    alignItems: "center",
    paddingVertical: 20,
  },
  imageShadowBox: {
    width: SCREEN_WIDTH * 0.55,
    height: SCREEN_HEIGHT * 0.3,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 12,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
      },
      android: { elevation: 8 },
    }),
    borderWidth: 1,
    borderColor: "#EFE8DA",
  },
  bookImage: { width: "100%", height: "100%", borderRadius: 4 },
  contentContainer: { paddingHorizontal: 24 },
  bentoActionContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 10,
    marginBottom: 25,
  },
  bentoActionBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "white",
    paddingVertical: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#EFE8DA",
    ...Platform.select({
      android: { elevation: 2 },
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
      },
    }),
  },
  activeLike: { backgroundColor: "#FFF1F2", borderColor: "#FECDD3" },
  activeSave: { backgroundColor: "#FFFBEB", borderColor: "#FEF3C7" },
  bentoActionText: { fontSize: 13, fontWeight: "800", color: "#64748B" },
  titleRow: { marginBottom: 12 },
  bookTitle: {
    fontSize: 28,
    fontWeight: "900",
    color: "#1A1A1A",
    lineHeight: 34,
    letterSpacing: -0.5,
  },
  authorText: {
    fontSize: 16,
    color: "#6B705C",
    marginTop: 4,
    fontWeight: "500",
  },
  authorName: { color: "#5c1616", fontWeight: "800" },
  badgeRow: { flexDirection: "row", alignItems: "center", marginBottom: 20 },
  badge: {
    backgroundColor: "#F3EEE0",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: "900",
    color: "#5c1616",
    letterSpacing: 0.5,
  },
  dotSeparator: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#CBD5E1",
    marginHorizontal: 12,
  },
  onlineBadge: { flexDirection: "row", alignItems: "center", gap: 6 },
  onlineDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#10B981",
  },
  onlineText: { fontSize: 12, fontWeight: "800", color: "#10B981" },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  statBox: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 22,
    paddingVertical: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#F1F5F9",
  },
  iconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 6,
  },
  statValue: { fontSize: 16, fontWeight: "900", color: "#1E293B" },
  statLabel: {
    fontSize: 9,
    fontWeight: "800",
    color: "#94A3B8",
    letterSpacing: 1,
  },
  divider: { height: 1, backgroundColor: "#F1F5F9", marginVertical: 24 },
  descriptionSection: { marginBottom: 20 },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  sectionHeading: {
    fontSize: 20,
    fontWeight: "900",
    color: "#1A1A1A",
  },
  descriptionText: {
    fontSize: 15,
    color: "#475569",
    lineHeight: 24,
    fontWeight: "400",
  },
  footerContainer: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
    paddingTop: 18,
    paddingHorizontal: 24,
    paddingBottom: Platform.OS === "ios" ? 34 : 24,
  },
  footerInner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  formatSection: { justifyContent: "center" },
  formatLabel: {
    fontSize: 10,
    fontWeight: "900",
    color: "#94A3B8",
    letterSpacing: 1.5,
  },
  formatValue: { fontSize: 22, fontWeight: "900", color: "#1A1A1A" },
  readButton: {
    backgroundColor: "#5c1616",
    paddingLeft: 24,
    paddingRight: 10,
    paddingVertical: 10,
    borderRadius: 24,
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
    ...Platform.select({
      android: { elevation: 6 },
      ios: {
        shadowColor: "#5c1616",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
    }),
  },
  readButtonText: { color: "#FFFFFF", fontSize: 17, fontWeight: "900" },
  readIconCircle: {
    backgroundColor: "#FBBF24",
    width: 44,
    height: 44,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
  },
});
