import { Dimensions, StyleSheet } from "react-native";

const { height: SCREEN_HEIGHT, width: SCREEN_WIDTH } = Dimensions.get("window");

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(15, 23, 42, 0.7)",
  },
  backdrop: { ...StyleSheet.absoluteFillObject },
  bottomSheet: {
    backgroundColor: "#F8FAFC",
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    maxHeight: SCREEN_HEIGHT * 0.9,
    width: "100%",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 24,
    paddingBottom: 10,
  },
  swapBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#CCFBF1",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    gap: 6,
  },
  swapBadgeText: {
    fontSize: 10,
    fontWeight: "900",
    color: "#0D9488",
    letterSpacing: 1,
  },
  closeBtn: {
    backgroundColor: "white",
    padding: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  scrollContent: { paddingBottom: 140 },
  offeredSection: {
    flexDirection: "row",
    paddingHorizontal: 24,
    marginTop: 10,
    gap: 20,
  },
  imageContainer: {
    width: 100,
    height: 140,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 8,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  bookImage: { width: "100%", height: "100%" },
  mainInfo: { flex: 1, justifyContent: "center" },
  bookLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: "#94A3B8",
    letterSpacing: 2,
    marginBottom: 4,
  },
  bookTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: "#1A1A1A",
    lineHeight: 26,
  },
  authorText: { fontSize: 14, color: "#64748B", marginTop: 4 },
  conditionPill: {
    alignSelf: "flex-start",
    backgroundColor: "#F1F5F9",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  conditionText: { fontSize: 9, fontWeight: "800", color: "#475569" },
  interactionRow: {
    flexDirection: "row",
    paddingHorizontal: 24,
    marginTop: 20,
    gap: 15,
  },
  actionItem: {
    width: 44,
    height: 44,
    backgroundColor: "white",
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  divider: {
    height: 1,
    backgroundColor: "#E2E8F0",
    marginHorizontal: 24,
    marginVertical: 24,
  },
  desiredCard: {
    marginHorizontal: 24,
    backgroundColor: "white",
    borderRadius: 28,
    padding: 20,
    borderWidth: 1,
    borderColor: "#CCFBF1",
    borderLeftWidth: 6,
    borderLeftColor: "#0D9488",
  },
  desiredHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 15,
  },
  desiredTitle: { fontSize: 16, fontWeight: "900", color: "#1A1A1A" },
  bentoGrid: { gap: 12 },
  bentoItem: {
    backgroundColor: "#F0FDFA",
    padding: 12,
    borderRadius: 12,
  },
  bentoLabel: {
    fontSize: 9,
    fontWeight: "800",
    color: "#0D9488",
    letterSpacing: 1,
  },
  bentoValue: {
    fontSize: 14,
    fontWeight: "800",
    color: "#1A1A1A",
    marginTop: 2,
  },
  statsStrip: {
    flexDirection: "row",
    paddingHorizontal: 24,
    marginTop: 24,
    gap: 10,
  },
  statChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    gap: 6,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  statChipText: { fontSize: 11, fontWeight: "700", color: "#64748B" },
  descriptionArea: { paddingHorizontal: 24, marginTop: 30 },
  sectionHeading: {
    fontSize: 14,
    fontWeight: "900",
    color: "#1A1A1A",
    marginBottom: 10,
  },
  descriptionText: { fontSize: 14, color: "#475569", lineHeight: 22 },
  footer: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    backgroundColor: "white",
    paddingHorizontal: 24,
    paddingVertical: 20,
    borderTopWidth: 1,
    borderTopColor: "#E2E8F0",
  },
  footerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  offerInfo: { justifyContent: "center" },
  offerLabel: { fontSize: 10, fontWeight: "800", color: "#94A3B8" },
  offerStatus: { fontSize: 15, fontWeight: "900", color: "#0D9488" },
  swapBtn: {
    backgroundColor: "#1A1A1A",
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    elevation: 8,
  },
  swapBtnText: { color: "white", fontSize: 15, fontWeight: "900" },
});
