import { Dimensions, StyleSheet } from "react-native";
const { height: SCREEN_HEIGHT, width: SCREEN_WIDTH } = Dimensions.get("window");

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0, 0, 0, 0.4)",
  },
  backdrop: { ...StyleSheet.absoluteFillObject },
  bottomSheet: {
    backgroundColor: "#FFFDF0",
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    maxHeight: SCREEN_HEIGHT * 0.85,
    width: "100%",
  },
  header: { alignItems: "center", paddingVertical: 14 },
  dragHandle: {
    width: 40,
    height: 5,
    backgroundColor: "#E5E0D5",
    borderRadius: 10,
  },
  closeButton: {
    position: "absolute",
    right: 20,
    top: 10,
    backgroundColor: "#F3EEE0",
    padding: 8,
    borderRadius: 12,
  },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 140 },
  heroSection: { flexDirection: "row", alignItems: "center", marginTop: 10 },
  imageWrapper: {
    width: 90,
    height: 120,
    backgroundColor: "white",
    borderRadius: 16,
    padding: 6,
    borderWidth: 1,
    borderColor: "#EFE8DA",
  },
  bookImage: { width: "100%", height: "100%", borderRadius: 8 },
  mainDetails: { flex: 1, marginLeft: 16 },
  bookTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: "#1A1A1A",
    lineHeight: 26,
  },
  authorText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#6B705C",
    marginTop: 4,
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    gap: 12,
  },
  priceText: { fontSize: 24, fontWeight: "900", color: "#5c1616" },
  qtyBadge: {
    backgroundColor: "#F3EEE0",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  qtyText: { fontSize: 11, fontWeight: "800", color: "#6B705C" },
  statsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 24 },
  statBox: {
    width: (SCREEN_WIDTH - 50) / 2,
    backgroundColor: "white",
    padding: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#EFE8DA",
    alignItems: "center",
  },
  statValue: {
    fontSize: 16,
    fontWeight: "900",
    color: "#1A1A1A",
    marginTop: 6,
  },
  statLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: "#A5A58D",
    letterSpacing: 1,
  },
  metaContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 20,
  },
  metaPill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F3EEE0",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 12,
    gap: 6,
  },
  metaLabel: { fontSize: 10, fontWeight: "700", color: "#6B705C" },
  metaText: { fontSize: 11, fontWeight: "900", color: "#5c1616" },
  descriptionSection: { marginTop: 25 },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: "#1A1A1A",
    marginBottom: 8,
  },
  descriptionText: {
    fontSize: 14,
    color: "#6B705C",
    lineHeight: 22,
    fontWeight: "500",
  },
  footer: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    backgroundColor: "white",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: "#EFE8DA",
  },
  footerContent: { flexDirection: "row", gap: 12 },
  deleteBtn: {
    width: 55,
    height: 55,
    borderRadius: 16,
    backgroundColor: "#FEF2F2",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#FEE2E2",
  },
  editBtn: {
    flex: 1,
    height: 55,
    borderRadius: 16,
    backgroundColor: "#1A1A1A",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
  },
  editBtnText: { color: "white", fontSize: 16, fontWeight: "800" },
});